### ISSUE TITLE
Language Functionality

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#12]
Spurtcms Admin allows to set a default language.could you extend the functionality to download the language file for user to his system?

**Comment by thayanithi-picco** [comment]
Thank you for raising this requirement. We have developed this feature shortly.

**Comment by thayanithi-picco** [comment]
This Feature was implemented. Please check and let us know your comments.
![Screenshot from 2024-05-28 10-58-57](https://github.com/spurtcms/spurtcms-admin/assets/144322751/816e877a-a660-43f5-827e-93e891d445fd)
