### ISSUE TITLE
Media Library

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#13]
Currently while uploading the images from media library,crop functionality is available.if you extend the functionality to resize the crop images as Thumbnail/portrait/Landscape that would allow us to project better images.

**Comment by ambiga-piccosoft** [comment]
Now implemented the Thumbnail/portrait/Landscape crop image.
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/5ec8ce04-065d-40cc-a1b9-ecb5f0770d5a)

**Comment by cms-coder** [comment]
Thank you for implementing the feature.Truly helpful
