### ISSUE TITLE
Roles and Permission

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#15]
Roles and permissions feature is beneficial to define multiple levels of access to the user. Additionally if you could allow the option to access the data which the user only created that super cede all the existing permissions,that would be helpful.

**Comment by ambiga-piccosoft** [comment]
Thank You So much for your query, we really appreciate your contribution towards spurt-cms. We will take up this feature request shortly.

**Comment by ambiga-piccosoft** [comment]
The user permission feature was implemented , please check and let us know your comments.
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/e35831cc-8db8-4caf-9ca3-fa3778cf047b)

**Comment by cms-coder** [comment]
Thank you.This is useful
