### ISSUE TITLE
Bulk Import

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#19]
Allow user to bulk create the entries for the channels selected.

**Comment by ambiga-piccosoft** [comment]
we will take on this in feature implementation.

**Comment by thayanithi-picco** [comment]
steps:
 step 1: login  into admin  spurt_cms

**Comment by cms-coder** [comment]
![logo](https://github.com/spurtcms/spurtcms-admin/assets/161009037/55da3a2b-211a-432f-9119-d592b1f00a59)

**Comment by cms-coder** [comment]
![logo](https://github.com/spurtcms/spurtcms-admin/assets/161009037/bd4ad030-b18d-4f49-b8fa-542185c08420)

**Comment by ambiga-piccosoft** [comment]
Please follow the below steps to start with bulk import
steps:
 step 1: login  into admin  spurt_cms
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/d1dde121-b4be-4192-a551-364c2efe2d7a)
step 2 :Go to Settings  tab 
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/974beffb-5659-48c3-94e1-576593f395dd)
step3 : Now Explore your bulk import feature
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/58088a00-cf29-4a40-8efb-6c304985d5f0)

**Comment by cms-coder** [comment]
Thank You.Will explore this space.

**Comment by cms-coder** [comment]
Hello,This feature is awesome,but while mapping the fields from my excel sometime am facing issues with mismatch.If you could introduce auto mapping for field header that would solve my issue.

**Comment by ambiga-piccosoft** [comment]
Thanks for your interest. We will look into the possibilities.

**Comment by ambiga-piccosoft** [comment]
@cms-coder ,As requested , we have implemented auto mapping feature which will be helpful.
Please browse on our new feature Auto mapping as shared in the screen below.
![image](https://github.com/spurtcms/spurtcms-admin/assets/133978862/ebfb5cd4-60b5-4111-8e9f-9bbf91cfc19e)
