### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#23]
Media tab is a generic feature in spurtcms currently placed under channels,but if we could create it as new tab that would be accessed throughout the application, will be excellent

**Comment by spurtcmsdeveloper-146** [comment]
Hello @cms-coder, As a developer, I agree that creating a new Media tab accessible throughout the application would be an excellent feature. This would allow users to easily access and manage media assets across different parts of the application, improving the overall user experience.
We will implement this feature shortly.

**Comment by spurtcmsdeveloper-146** [comment]
This suggestion was implemented. The media tab was made as a generic tab.

**Comment by cms-coder** [comment]
Thank you
