### ISSUE TITLE
Category group deletion

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#25]
On deleting the parent category all the child category and its references under it should be removed.

**Comment by ambiga-piccosoft** [comment]
Hello @cms-coder , Thank you for raising the issue.

**Comment by ambiga-piccosoft** [comment]
We worked upon deleting the child categories linked to the parent.On deleting the parent all the linked child categories were removed.

**Comment by cms-coder** [comment]
Yeah..its working fine now
