### ISSUE TITLE
X mins Reading time functionality

### ISSUE THREAD

**Issue by cms-coder** [spurtcms/spurtcms-admin#30]
Currently members can access the spcaes details and navigate through pages.If a lable to intimate the members on how long it would take to read a particular space is given upfront it will ease the readers to manage their time.

**Comment by nithya-picco** [comment]
Thank you for suggesting the reading time feature. Calculating and displaying reading time dynamically can enhance user experience.  And This feature was implemented.

**Comment by cms-coder** [comment]
Thanks
